import "@/styles/app.css";

export const metadata = {
  title: "Next.js Signin",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
