upstream backend-nestjs{
    server backend-soundcloud:8001;
}

upstream frontend-nextjs{
    server frontend-nextjs:3001;
}

server{
    listen 80;
    server_name localhost;

    location / {
        try_files $uri $uri/ @nextjs;
    }
    location @nextjs{
        proxy_pass http://frontend-nextjs;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x-forwarded_for;
        proxy_set_header Host $host;
        proxy_cache_bypass X-NginX-Proxy true;

        proxy_set_header X-Forwarded-Prefix /;
    }
    location /api{
        proxy_pass http://frontend-nextjs;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x-forwarded_for;
        proxy_set_header Host $host;
        proxy_cache_bypass X-NginX-Proxy true;
    }
}